fix(test) add data plane log checks to version compatibility tests
Since the `sync_status` is set by the control plane, a additional check
of the data plane logs needs to be performed in order to account for any
bad configurations sent to the data plane. If any error messages exist
that match the bad configuration pattern, they will be output to the
terminal and force a failed exit for Jenkins failure.

- Build and create a snapshot for sequential pipelines
- Update default data plane version
- Do not skip enterprise plugins
- Fix Jenkinsfile linting issues

diff --git a/.jenkins/smoke-tests b/.jenkins/smoke-tests
--- a/.jenkins/smoke-tests
+++ b/.jenkins/smoke-tests
@@ -12,7 +12,7 @@ void setBuildStatus(String message, String state) {
 // Generate the CLI parameters for any known incompatibilities
 def known_incompatibilities(String csv) {
   def known_incompatible = ""
-  if (! csv.isEmpty()) {
+  if (csv && ! csv.isEmpty()) {
     known_incompatible = '--known-incompatible ' + csv.split(',').join(' --known-incompatible ')
   }
   return known_incompatible
@@ -31,7 +31,7 @@ pipeline {
   parameters {
     string(
       name: 'DATA_PLANE_KONG_GATEWAY_IMAGE',
-      defaultValue: 'kong/kong-gateway:2.5',
+      defaultValue: 'kong/kong-gateway:2.7',
       trim: true,
       description: '''<p>Kong Gateway image to use for the data plane</p>
                       <ul>
@@ -42,7 +42,7 @@ pipeline {
                       <strong>Note</strong>: <b>kong/kong-gateway-internal</b> and <b>kong/kong-gateway-private</b> require 1Password credentials to login (see <i>kongcloudowner</i> for credentials)''')
     string(
       name: 'KNOWN_PLUGIN_INCOMPATIBILITIES',
-      defaultValue: 'jq',
+      defaultValue: '',
       trim: true,
       description: 'Comma separated list of known incompatible plugins')
     string(
@@ -60,6 +60,9 @@ pipeline {
 
     // Override gojira version (ensure master)
     GOJIRA_VERSION = 'master'
+    // Perform "magic dev" on source instance and build snapshots
+    GOJIRA_USE_SNAPSHOT = '1'
+    GOJIRA_MAGIC_DEV = '1'
 
     // Override PATH to include any binary installations
     PATH = "${env.PATH}:~/.local/bin"
@@ -103,6 +106,14 @@ pipeline {
            """
       }
     }
+    stage('Build Kong Gateway') {
+      steps {
+        sh label: 'Start Kong Gateway',
+           script: 'gojira up'
+        sh label: 'Clean Kong Gateway instance',
+           script: 'gojira nuke -f'
+      }
+    }
     stage('Version Compatibility') {
       when {
         anyOf {
@@ -114,11 +125,14 @@ pipeline {
                 branch 'main'
               }
             }
-            anyOf {
-              changeset "kong/plugins/**"
-              changeset "kong/enterprise_edition/redis/**"
-              changeset "kong-*.rockspec"
-            }
+            // Commenting this out for now because other schema changes can
+            // effect version compatibilty outside of plugins and the shared
+            // Redis configuration
+            // anyOf {
+            //   changeset "kong/plugins/**"
+            //   changeset "kong/enterprise_edition/redis/**"
+            //   changeset "kong-*.rockspec"
+            // }
           }
         }
       }
@@ -135,17 +149,31 @@ pipeline {
            script: '''gojira hybrid run@kong-dp \
                         --dataplane-image $DATA_PLANE_KONG_GATEWAY_IMAGE \
                         -e KONG_LICENSE_DATA \
-                          kong start'''
+                          kong start -vv'''
         sh label: 'Execute version compatibility smoke test',
            script: '''gojira hybrid run@kong-cp \
                         --dataplane-image $DATA_PLANE_KONG_GATEWAY_IMAGE \
                         -e KONG_LICENSE_DATA \
                         -e GITHUB_TOKEN \
-                          /check-version-compatibility --skip-enterprise ''' + known_incompatibilities(env.KNOWN_PLUGIN_INCOMPATIBILITIES)
-        sh label: 'Clean gojira instances',
-           script: '''gojira hybrid nuke \
-                        --dataplane-image $DATA_PLANE_KONG_GATEWAY_IMAGE \
-                        -f'''
+                          /check-version-compatibility ''' + known_incompatibilities(env.KNOWN_PLUGIN_INCOMPATIBILITIES)
+        sh label: 'Check for data plane errors and clean gojira instances',
+           script: '''
+             CONFIG_ERRORS="$(gojira hybrid run@kong-dp \
+               --dataplane-image $DATA_PLANE_KONG_GATEWAY_IMAGE \
+               cat /kong/servroot/logs/error.log | \
+                 sed -n '/unable to update running config/,/context: ngx.timer$/p')"
+             if [[ -n $CONFIG_ERRORS ]]; then
+               printf "Version Compatibility Errors Occurred\n------------------------------\n\n"
+               printf "%s\n\n" "$CONFIG_ERRORS"
+               VC_FAILED=1
+             fi
+
+             gojira hybrid nuke \
+               --dataplane-image $DATA_PLANE_KONG_GATEWAY_IMAGE \
+               -f
+
+             [[ -z ${VC_FAILED+x} ]] || exit 2
+            '''
       }
     }
     stage('Apache Cassandra Migrations') {
@@ -163,7 +191,7 @@ pipeline {
   }
   post {
     always {
-      sh label: 'Clean Gojira Installation'
+      sh label: 'Clean Gojira Installation',
          script: 'rm -rf /tmp/gojira ~/.local/bin/gojira'
     }
     success {
