fix(scripts) Check requirements before doing anything

diff --git a/scripts/make-patch-release b/scripts/make-patch-release
--- a/scripts/make-patch-release
+++ b/scripts/make-patch-release
@@ -38,6 +38,27 @@ function usage() {
 }
 
 #-------------------------------------------------------------------------------
+function need() {
+  req="$1"
+
+  if [ -z $(which "$req") ]; then
+     echo "Required command $req not found."
+     exit 1
+  fi
+}
+
+function check_requirements() {
+   need git
+   need hub
+   need sed
+
+   if [[ ! "$(sed --version)" =~ "GNU sed" ]]; then
+      echo "FAIL: sed command isn't GNU."
+      exit 1
+   fi
+}
+
+#-------------------------------------------------------------------------------
 # Default help
 #-------------------------------------------------------------------------------
 
@@ -50,6 +71,8 @@ fi
 #-------------------------------------------------------------------------------
 # Variables
 #-------------------------------------------------------------------------------
+
+check_requirements
 
 version="$1"
 step="$2"
