chore(ci): support building ngx_wasm_module

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -141,7 +141,7 @@ jobs:
         ./configure --prefix=/usr/local/git
         make -j$(nproc)
         make install
-    
+
     - name: Add Git to PATH
       if: matrix.package == 'rpm' || matrix.image == 'ubuntu:18.04'
       run: |
@@ -202,6 +202,22 @@ jobs:
         yum groupinstall -y 'Development Tools'
         dnf config-manager --set-enabled powertools || true # enable devel packages on rockylinux:8
         yum install -y libyaml-devel
+
+    - name: Set ngx_wasm_module path/branch vars
+      run: |
+        grep ^NGX_WASM_MODULE_BRANCH= .requirements >> $GITHUB_ENV || {
+          echo "ERROR: NGX_WASM_MODULE_BRANCH is not defined in .requirements"
+          exit 1
+        }
+        echo "NGX_WASM_MODULE_REMOTE=$PWD/ngx_wasm_module" >> $GITHUB_ENV
+
+    - name: Checkout ngx_wasm_module
+      uses: actions/checkout@v3
+      with:
+        repository: Kong/ngx_wasm_module
+        path: ${{ env.NGX_WASM_MODULE_REMOTE }}
+        ref: ${{ env.NGX_WASM_MODULE_BRANCH }}
+        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
 
     - name: Build Kong dependencies
       if: steps.cache-deps.outputs.cache-hit != 'true'
